// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupProcesses() {
  return window['go']['main']['App']['CleanupProcesses']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function CreatePrefix(arg1) {
  return window['go']['main']['App']['CreatePrefix'](arg1);
}

export function DetectLosslessDll() {
  return window['go']['main']['App']['DetectLosslessDll']();
}

export function EditLsfgConfigForGame(arg1) {
  return window['go']['main']['App']['EditLsfgConfigForGame'](arg1);
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetExeIcon(arg1) {
  return window['go']['main']['App']['GetExeIcon'](arg1);
}

export function GetInitialGamePath() {
  return window['go']['main']['App']['GetInitialGamePath']();
}

export function GetInitialLauncherPath() {
  return window['go']['main']['App']['GetInitialLauncherPath']();
}

export function GetListGpus() {
  return window['go']['main']['App']['GetListGpus']();
}

export function GetLsfgProfileForGame(arg1) {
  return window['go']['main']['App']['GetLsfgProfileForGame'](arg1);
}

export function GetPrefixBaseDir() {
  return window['go']['main']['App']['GetPrefixBaseDir']();
}

export function GetProtonReleases(arg1) {
  return window['go']['main']['App']['GetProtonReleases'](arg1);
}

export function GetProtonVariants() {
  return window['go']['main']['App']['GetProtonVariants']();
}

export function GetShouldEditLsfg() {
  return window['go']['main']['App']['GetShouldEditLsfg']();
}

export function GetSystemToolsStatus() {
  return window['go']['main']['App']['GetSystemToolsStatus']();
}

export function GetTotalRam() {
  return window['go']['main']['App']['GetTotalRam']();
}

export function GetUtilsStatus() {
  return window['go']['main']['App']['GetUtilsStatus']();
}

export function InstallLsfg() {
  return window['go']['main']['App']['InstallLsfg']();
}

export function InstallProtonVersion(arg1, arg2) {
  return window['go']['main']['App']['InstallProtonVersion'](arg1, arg2);
}

export function ListPrefixes() {
  return window['go']['main']['App']['ListPrefixes']();
}

export function LoadPrefixConfig(arg1) {
  return window['go']['main']['App']['LoadPrefixConfig'](arg1);
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function PickFileCustom(arg1, arg2) {
  return window['go']['main']['App']['PickFileCustom'](arg1, arg2);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RemoveProfile(arg1) {
  return window['go']['main']['App']['RemoveProfile'](arg1);
}

export function RunGame(arg1, arg2) {
  return window['go']['main']['App']['RunGame'](arg1, arg2);
}

export function RunPrefixTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunPrefixTool'](arg1, arg2, arg3);
}

export function SaveLsfgProfile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveLsfgProfile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SavePrefixConfig(arg1, arg2) {
  return window['go']['main']['App']['SavePrefixConfig'](arg1, arg2);
}

export function ScanProtonVersions() {
  return window['go']['main']['App']['ScanProtonVersions']();
}

export function UninstallLsfg() {
  return window['go']['main']['App']['UninstallLsfg']();
}
