// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launcher} from '../models';

export function PickFile():Promise<string>;

export function PickFolder():Promise<string>;

export function RunGame(arg1:launcher.LaunchOptions,arg2:boolean):Promise<void>;

export function RunPrefixTool(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ScanProtonVersions():Promise<Array<launcher.ProtonTool>>;
