// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RunGame(arg1, arg2) {
  return window['go']['main']['App']['RunGame'](arg1, arg2);
}

export function RunPrefixTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunPrefixTool'](arg1, arg2, arg3);
}

export function ScanProtonVersions() {
  return window['go']['main']['App']['ScanProtonVersions']();
}
